### ISSUE TITLE
Wrong statement that - The type of `null` is wrongly computed to be Object

### ISSUE THREAD

**Issue by demimurych** [carltheperson/advanced-js-objects#3]
https://github.com/carltheperson/advanced-js-objects/blob/b8d9217bcd80b2d1b1f35ba83bbc6e47de4152f2/chapters/chapter-1.md?plain=1#L212

>The type of `null` is wrongly computed to be Object. This is a bug that was introduced in the first implementation of JavaScript

According to the [specification](https://tc39.es/ecma262/#sec-null-value), null primitive value that represents the intentional absence of any object value.  **It's not a mistake. And perfectly correct behavior.**

For two reasons:
1. typeOf is a unary operator that does not return a "type" value.
2. Null in JS is a type indicating that the current link is an object that has no structure defined. It is extremely important for the interpreter to know and understand the difference between undefined for referers and null for objects.

A typical use case is when an API or function must return an object, but for some reason this cannot be done (for example, an error) in this case, the function must return null.

This is exactly the same behavior as NaN for floating point numbers.

The link https://2ality.com/2013/10/typeof-null.html brings a lot of confusion.
1)  "I think it is too late to fix typeof. The change proposed for typeof null will break existing code." 
      This is not about JS code. Its about the C code that implements the work of JS in host.
  
2) Null is lexically ambiguous. On the one hand, this is a primitive value. On the other hand, this is the Object. 
    That is what is the problem. Not a bug in the code that led to the wrong answer. 
    
    If you look at the code in post  https://2ality.com/2013/10/typeof-null.html, you will see that there is no code that would report such a type as "null". It does not exist precisely because the logic of the operation of Null is the logic of the operation of the object.

Here this post https://2ality.com/2013/05/history-undefined.html covers the problem more correctly.

For this reason, it is completely wrong to say that typeof null === "object " is a mistake. Which is confirmed as the current specification. 
So is an explanation as to why Null has "two types".

**Comment by carltheperson** [comment]
Thanks for opening this issue. 

This depends what purpose you expect the `typeof` operator to have. The specification doesn't say this and only describes which values `typeof` should return and when.

I would think that the purpose of `typeof` is to provide the **type** of a value. I think this is a fair assumption based on the name and functionality (excluding `null`) that `typeof` has. Given my assumption, `typeof null === "object"` is wrong. 

Even if `null`  is used as an intentional absence of any object value, it's still a separate type. 

Also, I'm not saying that `typeof null === "object"` is a mistake, I'm saying that it's wrong. I agree that `typeof` adheres to the specification perfectly.

It currently being in the language is not a mistake. Even if it **was** caused by a mistake made by Brendan Eich who wrote the original code and calls it a "bug".

I'll happily reference your issue in the footnotes to provide more nuance for the readers.
